### ISSUE TITLE
Hide "Random" icon not working at 1st launch

### ISSUE THREAD

**Issue by DjKaijin** [Gabisonfire/SteamDock#1]
[MainWindow.xaml.cs.zip](https://github.com/Gabisonfire/SteamDock/files/1382886/MainWindow.xaml.cs.zip)

I apologize if this isn't the correct place but I wanted to contact you due to an issue I was having with your amazing SteamDock app and I also wanted to have the option to choose the size 96 for the game icons.
Every time I ran the app and the checkbox for the Hide "Random" icon was selected, if I didn't deselect and reselect it, the icon would appear when I pressed "Launch".
I'm taking a 2 year programming course, mainly C#, Object Oriented Programming (I hope that's the correct expression), I finished the 1st year in July and just started the 2nd year 1 month ago but I'm still at a beginner level.
I decided to download the solution and see if I could make the Random icon stay hidden at 1st launch without the need to deselect->reselect the radiobutton.
At 1st most of the code was totally strange to me but thanks to the comments you placed I think I understood enough to try to "solve" my issue and add the icon size I wanted. The 96px size was relatively easy, I got it working at 1st try. As for the Random icon, well, that took a little longer. :)
After several attempts I believe it's working and despite the fact that I changed and reverted several lines of code, in the end I think the only one I changed was:
public static bool hideRandomIcon = true;              // Setting to hide random icon
to:
public static bool hideRandomIcon = false;              // Setting to hide random icon
in the MainWindow.xaml.cs file.
I uploaded the .cs file that I changed. I wanted to upload the entire solution but for some reason I don't understand why the size of the solution I modified on my pc is 52.3MB and unfortunately I couldn't find a way to .zip, .rar or even .7z in a file <10MB, which is the max file size permitted.
I hope you don't mind me changing your project, I didn't share it with anybody else and I thought I should try to contact you to find out if the problem I was having had to do with something on my end or if it was really a matter of changing the code a little bit.
Thanks for creating this amazing tool, I only discovered it recently but I've been using it since then.
Best Regards,
Nuno Sousa

**Comment by Gabisonfire** [comment]
Hi Nuno,

I'm really glad you like my project! You indeed spotted a bug in my code, I'll look over the changes you suggested. The size of the project is probably high due to the icons you download on the first launch since I have stripped them from the repo. Since you are starting to learn and to contribute, I highly suggest you familiarize yourself with git in general to be able to easily contribute to project.

Normally in our case, you would've made a "Pull Request" where you would basically submit your code to me for review where I can take a look and then _merge_ it into the main branch.

Thank you again for spotting this error, i'll try to get it fixed asap :)

**Comment by DjKaijin** [comment]
Hi Gabisonfire,

Thanks for the quick reply and all the information you provided, it will be very useful.
In the future I'll do as you explained, I never contributed in any project before, thus I wasn't very sure how to properly proceed.
After reading your reply I managed to eliminate the unnecessary files from my project folder and was able to put the solution in a .zip file of the same size as yours. I should have commented the changes I made, sorry, I only realized that now.
I'm very glad I was able to help and there's no need to thank me, it was a pleasure and a challenge. :)
[SteamDock-master_changed.zip](https://github.com/Gabisonfire/SteamDock/files/1383144/SteamDock-master_changed.zip)

**Comment by Gabisonfire** [comment]
I'm thanking you anyways :)

I'll take a look at it during the weekend.

I'm really curious of where did you hear from my dock?

**Comment by DjKaijin** [comment]
You're most welcome.
I found out about your dock here http://steamcommunity.com/sharedfiles/filedetails/?id=451698754
It's a pretty big guide, I was checking every section to see if there was something that would be handy and when I reached the "Softwares" yours was there...... 

> SteamGameLauncher[github.com]
> Created by: Gabisonfire
> Description: Creates a launch pad for your installed games.

I think it's not with the correct name, but that's how I found your dock :)

**Comment by Gabisonfire** [comment]
Great, yeah I recently changed the name

**Comment by Gabisonfire** [comment]
Fixed, issue with the logic when loading the settings from the config file.

**Comment by DjKaijin** [comment]
Thanks!
